In [51]:
data_s1 = {
    'EmpID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Evan', 'A', 'B', 'C', 'D', 'E'],
    'Age': [32, 30, 32, 32, 30, 30, 32, 30, 32, 28],
    'Dept': ['IT', 'HR', 'IT', 'Marketing', 'IT',
             'HR', 'Marketing', 'HR', 'Marketing', 'Marketing',],
    'Salary': [75000.0, 60000.0, 82000.0, 65000.0, 90000.0,
               75000.0, 60000.0, 82000.0, 65000.0, 90000.0,
               ]
}

print(data_s1)

{'EmpID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110], 'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Evan', 'A', 'B', 'C', 'D', 'E'], 'Age': [32, 30, 32, 32, 30, 30, 32, 30, 32, 28], 'Dept': ['IT', 'HR', 'IT', 'Marketing', 'IT', 'HR', 'Marketing', 'HR', 'Marketing', 'Marketing'], 'Salary': [75000.0, 60000.0, 82000.0, 65000.0, 90000.0, 75000.0, 60000.0, 82000.0, 65000.0, 90000.0]}

In [52]:
import pandas as pd
import numpy as np

In [53]:
df = pd.DataFrame(data_s1)
display(df)

   EmpID     Name  Age       Dept   Salary
0    101    Alice   32         IT  75000.0
1    102      Bob   30         HR  60000.0
2    103  Charlie   32         IT  82000.0
3    104    Diana   32  Marketing  65000.0
4    105     Evan   30         IT  90000.0
5    106        A   30         HR  75000.0
6    107        B   32  Marketing  60000.0
7    108        C   30         HR  82000.0
8    109        D   32  Marketing  65000.0
9    110        E   28  Marketing  90000.0

In [54]:
# Colunms
print(df.columns)
print(df.columns.values)

# first column
print(df.columns.values[0])

#last column
print(df.columns.values[-1])

# only first two columns
print(df.columns[0:2])

# only alternate columns
print(df.columns[0:-1:2])

Index(['EmpID', 'Name', 'Age', 'Dept', 'Salary'], dtype='object')
['EmpID' 'Name' 'Age' 'Dept' 'Salary']
EmpID
Salary
Index(['EmpID', 'Name'], dtype='object')
Index(['EmpID', 'Age'], dtype='object')

### Slecting Columns

In [55]:
# select specific column
display(df[ ['Name', 'Salary'] ])

# select * (all colummns)
# display(df[df.columns])
print('All columns')
display(df)

# select first two columns
print('First two columns')
display(df[df.columns[0:2]])

print('Last two columns')
display(df[df.columns[-2:]])

print("Alternate columns")
display(df[   df.columns[0:-1:2] ])

      Name   Salary
0    Alice  75000.0
1      Bob  60000.0
2  Charlie  82000.0
3    Diana  65000.0
4     Evan  90000.0
5        A  75000.0
6        B  60000.0
7        C  82000.0
8        D  65000.0
9        E  90000.0

All columns

   EmpID     Name  Age       Dept   Salary
0    101    Alice   32         IT  75000.0
1    102      Bob   30         HR  60000.0
2    103  Charlie   32         IT  82000.0
3    104    Diana   32  Marketing  65000.0
4    105     Evan   30         IT  90000.0
5    106        A   30         HR  75000.0
6    107        B   32  Marketing  60000.0
7    108        C   30         HR  82000.0
8    109        D   32  Marketing  65000.0
9    110        E   28  Marketing  90000.0

First two columns

   EmpID     Name
0    101    Alice
1    102      Bob
2    103  Charlie
3    104    Diana
4    105     Evan
5    106        A
6    107        B
7    108        C
8    109        D
9    110        E

Last two columns

        Dept   Salary
0         IT  75000.0
1         HR  60000.0
2         IT  82000.0
3  Marketing  65000.0
4         IT  90000.0
5         HR  75000.0
6  Marketing  60000.0
7         HR  82000.0
8  Marketing  65000.0
9  Marketing  90000.0

Alternate columns

   EmpID  Age
0    101   32
1    102   30
2    103   32
3    104   32
4    105   30
5    106   30
6    107   32
7    108   30
8    109   32
9    110   28

In [56]:
# Selecting rows

# First row
display(df[ 0:1 ])

# First two rows
display(df[ 0:2 ])

# Last row
display(df[ -1: ])

# First three rows
display(df.head(3))

# Last three rows
display(df.tail(3))

   EmpID   Name  Age Dept   Salary
0    101  Alice   32   IT  75000.0

   EmpID   Name  Age Dept   Salary
0    101  Alice   32   IT  75000.0
1    102    Bob   30   HR  60000.0

   EmpID Name  Age       Dept   Salary
9    110    E   28  Marketing  90000.0

   EmpID     Name  Age Dept   Salary
0    101    Alice   32   IT  75000.0
1    102      Bob   30   HR  60000.0
2    103  Charlie   32   IT  82000.0

   EmpID Name  Age       Dept   Salary
7    108    C   30         HR  82000.0
8    109    D   32  Marketing  65000.0
9    110    E   28  Marketing  90000.0

### Series

In [57]:
# Series:
df['Name']

0      Alice
1        Bob
2    Charlie
3      Diana
4       Evan
5          A
6          B
7          C
8          D
9          E
Name: Name, dtype: object

### Data stats

In [58]:
df.describe()

           EmpID        Age        Salary
count   10.00000  10.000000     10.000000
mean   105.50000  30.800000  74400.000000
std      3.02765   1.398412  11520.030864
min    101.00000  28.000000  60000.000000
25%    103.25000  30.000000  65000.000000
50%    105.50000  31.000000  75000.000000
75%    107.75000  32.000000  82000.000000
max    110.00000  32.000000  90000.000000

In [59]:
#Categorical
display(df[['Dept']].describe())

# Numeric
df[['Salary']].describe()

             Dept
count          10
unique          3
top     Marketing
freq            4

             Salary
count     10.000000
mean   74400.000000
std    11520.030864
min    60000.000000
25%    65000.000000
50%    75000.000000
75%    82000.000000
max    90000.000000

In [60]:
# Frequency distribution of a Column
display(df[['Dept']].value_counts())

new_df = df[['Dept']].value_counts()

# print('--------------')
# display(df[['Dept', 'Name']].value_counts())

Dept
Marketing    4
HR           3
IT           3
Name: count, dtype: int64

In [61]:
display(new_df.transpose())

Dept
Marketing    4
HR           3
IT           3
Name: count, dtype: int64

In [62]:
df.transpose()
display(df)
display(df.transpose())

   EmpID     Name  Age       Dept   Salary
0    101    Alice   32         IT  75000.0
1    102      Bob   30         HR  60000.0
2    103  Charlie   32         IT  82000.0
3    104    Diana   32  Marketing  65000.0
4    105     Evan   30         IT  90000.0
5    106        A   30         HR  75000.0
6    107        B   32  Marketing  60000.0
7    108        C   30         HR  82000.0
8    109        D   32  Marketing  65000.0
9    110        E   28  Marketing  90000.0

,0,1,2,3,4,5,6,7,8,9
EmpID,101,102,103,104,105,106,107,108,109,110
Name,Alice,Bob,Charlie,Diana,Evan,A,B,C,D,E
Age,32,30,32,32,30,30,32,30,32,28
Dept,IT,HR,IT,Marketing,IT,HR,Marketing,HR,Marketing,Marketing
Salary,75000.0,60000.0,82000.0,65000.0,90000.0,75000.0,60000.0,82000.0,65000.0,90000.0

### Aggregation against rows

In [63]:
pd.DataFrame(df[ ['Age', 'Salary']].sum()).transpose()

     Age    Salary
0  308.0  744000.0

In [64]:
# Sum of Salary of all rows:
print(f"Total Salary: { df[['Salary']].sum().values[0] }")

# Sum of Salary of first two rows:
print(f"Total Salary of first two persons: { df[['Salary']][0:2].sum().values[0] }")

Total Salary: 744000.0
Total Salary of first two persons: 135000.0

In [65]:
print(f" Number of rows: { df[['Name']].count().values[0] }")

 Number of rows: 10

In [66]:
df[['Salary']].min()

Salary    60000.0
dtype: float64

In [67]:
df[ ['Salary'] ].max()

Salary    90000.0
dtype: float64

In [68]:
# Frequency distribution on Age
df[['Age']].value_counts()

Age
32     5
30     4
28     1
Name: count, dtype: int64

In [69]:
print(df['Salary'].max())
print()
print(df[['Salary']].max())
print('\n------\n')
print("Series: \n%s" % df['Salary'])
print()
print("Dataframe: \n%s" % df[['Salary']])

90000.0

Salary    90000.0
dtype: float64

------

Series:
0    75000.0
1    60000.0
2    82000.0
3    65000.0
4    90000.0
5    75000.0
6    60000.0
7    82000.0
8    65000.0
9    90000.0
Name: Salary, dtype: float64

Dataframe:
    Salary
0  75000.0
1  60000.0
2  82000.0
3  65000.0
4  90000.0
5  75000.0
6  60000.0
7  82000.0
8  65000.0
9  90000.0

### Row filters
'Where' clause in SQL

In [70]:
# 1 row, with name = Alice
df[ df['Name'] == 'Alice' ]

   EmpID   Name  Age Dept   Salary
0    101  Alice   32   IT  75000.0

In [71]:
# Filter to exclude Alice
df[ df['Name'] != 'Alice' ]

   EmpID     Name  Age       Dept   Salary
1    102      Bob   30         HR  60000.0
2    103  Charlie   32         IT  82000.0
3    104    Diana   32  Marketing  65000.0
4    105     Evan   30         IT  90000.0
5    106        A   30         HR  75000.0
6    107        B   32  Marketing  60000.0
7    108        C   30         HR  82000.0
8    109        D   32  Marketing  65000.0
9    110        E   28  Marketing  90000.0

In [72]:
# filter all rows, who are working in IT
df[ df['Dept'] == 'IT' ]

   EmpID     Name  Age Dept   Salary
0    101    Alice   32   IT  75000.0
2    103  Charlie   32   IT  82000.0
4    105     Evan   30   IT  90000.0

In [73]:
# filter 1 row, with max salary
max = df[['Salary']].max().values[0]
df[ df['Salary'] == max ]

   EmpID  Name  Age       Dept   Salary
4    105  Evan   30         IT  90000.0
9    110     E   28  Marketing  90000.0

Above works, but it has a few minor inefficiencies: it shadows Python's built-in max function, extracts the value using .values[0] unnecessarily, and creates a DataFrame subset [['Salary']] instead of a faster Series ['Salary'].

Here are the best ways to optimize this depending on how you want to handle ties (multiple rows having the same max salary):

In [74]:
df[ df['Salary'] == df['Salary'].max() ]

   EmpID  Name  Age       Dept   Salary
4    105  Evan   30         IT  90000.0
9    110     E   28  Marketing  90000.0

In [75]:
# All except the heighest salary
df[ df['Salary'] != df['Salary'].max() ]

   EmpID     Name  Age       Dept   Salary
0    101    Alice   32         IT  75000.0
1    102      Bob   30         HR  60000.0
2    103  Charlie   32         IT  82000.0
3    104    Diana   32  Marketing  65000.0
5    106        A   30         HR  75000.0
6    107        B   32  Marketing  60000.0
7    108        C   30         HR  82000.0
8    109        D   32  Marketing  65000.0

In [76]:
# filter all rows, who are working in IT
# Add add / aggregate all their salaries
'''
 SELECT SUM(SALARY)
 FROM EMPLOYEE
 WHERE DEPT IS 'IT'
'''
df[ df['Dept'] == 'IT' ][['Salary']].sum()

Salary    247000.0
dtype: float64

In [77]:
'''
 SELECT AVG(AGE)
 FROM EMPLOYEE
 WHERE DEPT IS 'IT'
'''
df[ df['Dept'] == 'IT' ][['Age']].mean()

Age    31.333333
dtype: float64

### Sorting

In [78]:
#  Sort by Salary, in descending order
df.sort_values(by='Salary', ascending=False)

   EmpID     Name  Age       Dept   Salary
9    110        E   28  Marketing  90000.0
4    105     Evan   30         IT  90000.0
7    108        C   30         HR  82000.0
2    103  Charlie   32         IT  82000.0
5    106        A   30         HR  75000.0
0    101    Alice   32         IT  75000.0
8    109        D   32  Marketing  65000.0
3    104    Diana   32  Marketing  65000.0
1    102      Bob   30         HR  60000.0
6    107        B   32  Marketing  60000.0

In [93]:
# Find top three departments with highest salaries
df.sort_values(by='Salary', ascending=False).head(3)[['Dept', 'Salary']].value_counts()

Dept       Salary
HR         82000.0    1
IT         90000.0    1
Marketing  90000.0    1
Name: count, dtype: int64

### Group By and aggregation

In [98]:
# Group BY Department, and count employees per department
print(df.groupby(by='Dept')[['EmpID']].count()['EmpID'].sum())
display(df.groupby(by='Dept')[['EmpID']].count())

10

           EmpID
Dept
HR             3
IT             3
Marketing      4

In [99]:
df.groupby(by='Age')[['Dept']].count()

     Dept
Age
28      1
30      4
32      5

In [101]:
display(df.groupby(by='Age')[['Salary']].sum())
display(df.groupby(by='Dept')[['Salary']].sum())

       Salary
Age
28    90000.0
30   307000.0
32   347000.0

             Salary
Dept
HR         217000.0
IT         247000.0
Marketing  280000.0

In [102]:
# Don't group-by primary-key, or unique-key ==> No grouping advantage
display(df.groupby(by='EmpID')[['Salary']].sum())

        Salary
EmpID
101    75000.0
102    60000.0
103    82000.0
104    65000.0
105    90000.0
106    75000.0
107    60000.0
108    82000.0
109    65000.0
110    90000.0

In [81]:
df.groupby(by='Age')[['Dept']].value_counts()

Age  Dept
28   Marketing    1
30   HR           3
     IT           1
32   Marketing    3
     IT           2
Name: count, dtype: int64

In [82]:
# Same as above, but results into a series
df.groupby(by='Dept')['Dept'].count()

# Can also be done using:
# df[['Dept']].value_counts()

Dept
HR           3
IT           3
Marketing    4
Name: Dept, dtype: int64

In [83]:
# Group by Dept, sum of salaries by department.
df.groupby(by='Dept', group_keys=['Dept'])[['Salary']].sum()

             Salary
Dept
HR         217000.0
IT         247000.0
Marketing  280000.0

#### Group By, with filters (SQL 'having')

In [106]:
# Group by Dept, sum of salaries by department, having aggregated-salary > 62000
df.groupby(by='Dept', group_keys=['Dept'])[['Salary']].sum().query('Salary > 220000.0')

             Salary
Dept
IT         247000.0
Marketing  280000.0

In [107]:
# Alt:
grouped_series = df.groupby(by='Dept', group_keys=['Dept'])[['Salary']].sum()
grouped_series[ grouped_series['Salary'] > 220000.0 ]

             Salary
Dept
IT         247000.0
Marketing  280000.0

In [111]:
# Find all departments where the number of employees in the department is more than 3
grouped_count_df = df.groupby(by='Dept')[['Dept']].count()
grouped_filtered_df = grouped_count_df.query('Dept > 2')
display(grouped_filtered_df)
print("Keys: %s" % list(grouped_filtered_df.keys()))
print("Values: %s" % grouped_filtered_df.values)

           Dept
Dept
HR            3
IT            3
Marketing     4

Keys: ['Dept']
Values: [[3]
 [3]
 [4]]

In [112]:
# Same as columns
df_keys = df.keys()
print("DF Keys: %s" % list(df_keys))
df_values = df.values
print("DF Values: %s" % list(df_values))

# print(dict(zip(df_keys, df_values)))

DF Keys: ['EmpID', 'Name', 'Age', 'Dept', 'Salary']
DF Values: [array([101, 'Alice', 32, 'IT', 75000.0], dtype=object), array([102, 'Bob', 30, 'HR', 60000.0], dtype=object), array([103, 'Charlie', 32, 'IT', 82000.0], dtype=object), array([104, 'Diana', 32, 'Marketing', 65000.0], dtype=object), array([105, 'Evan', 30, 'IT', 90000.0], dtype=object), array([106, 'A', 30, 'HR', 75000.0], dtype=object), array([107, 'B', 32, 'Marketing', 60000.0], dtype=object), array([108, 'C', 30, 'HR', 82000.0], dtype=object), array([109, 'D', 32, 'Marketing', 65000.0], dtype=object), array([110, 'E', 28, 'Marketing', 90000.0], dtype=object)]

### Joins (Inner)

#### Order Table

In [121]:
data_s2 = {
    'EmpID': [101, 102, 103, 104, 101, 102, 103, 101 ],
    'OrdId': ['ORD1', 'ORD2', 'ORD3', 'ORD4', 'ORD5', 'ORD6', 'ORD7', 'ORD8'],
    'Amount': [100, 150, 50, 600, 100, 80, 20, 50],
}
df2 = pd.DataFrame(data_s2)
display(df2)

   EmpID OrdId  Amount
0    101  ORD1     100
1    102  ORD2     150
2    103  ORD3      50
3    104  ORD4     600
4    101  ORD5     100
5    102  ORD6      80
6    103  ORD7      20
7    101  ORD8      50

In [122]:
display(df2.groupby(by='EmpID')[['OrdId']].count())
display(df2.groupby(by='EmpID')[['Amount']].sum().query('Amount > 500'))

       OrdId
EmpID
101        3
102        2
103        2
104        1

       Amount
EmpID
104       600

In [125]:
pd.merge(df, df2,
         # Optional
         on='EmpID',
         # By default it is inner
         #how='inner'
         )

   EmpID     Name  Age       Dept   Salary OrdId  Amount
0    101    Alice   32         IT  75000.0  ORD1     100
1    101    Alice   32         IT  75000.0  ORD5     100
2    101    Alice   32         IT  75000.0  ORD8      50
3    102      Bob   30         HR  60000.0  ORD2     150
4    102      Bob   30         HR  60000.0  ORD6      80
5    103  Charlie   32         IT  82000.0  ORD3      50
6    103  Charlie   32         IT  82000.0  ORD7      20
7    104    Diana   32  Marketing  65000.0  ORD4     600

In [126]:
pd.merge(df, df2,
         # Optional
         on='EmpID',
         how='left'
         )

    EmpID     Name  Age       Dept   Salary OrdId  Amount
0     101    Alice   32         IT  75000.0  ORD1   100.0
1     101    Alice   32         IT  75000.0  ORD5   100.0
2     101    Alice   32         IT  75000.0  ORD8    50.0
3     102      Bob   30         HR  60000.0  ORD2   150.0
4     102      Bob   30         HR  60000.0  ORD6    80.0
5     103  Charlie   32         IT  82000.0  ORD3    50.0
6     103  Charlie   32         IT  82000.0  ORD7    20.0
7     104    Diana   32  Marketing  65000.0  ORD4   600.0
8     105     Evan   30         IT  90000.0   NaN     NaN
9     106        A   30         HR  75000.0   NaN     NaN
10    107        B   32  Marketing  60000.0   NaN     NaN
11    108        C   30         HR  82000.0   NaN     NaN
12    109        D   32  Marketing  65000.0   NaN     NaN
13    110        E   28  Marketing  90000.0   NaN     NaN

In [127]:
pd.merge(df, df2,
         # Optional
         on='EmpID',
         how='right'
         )

   EmpID     Name  Age       Dept   Salary OrdId  Amount
0    101    Alice   32         IT  75000.0  ORD1     100
1    102      Bob   30         HR  60000.0  ORD2     150
2    103  Charlie   32         IT  82000.0  ORD3      50
3    104    Diana   32  Marketing  65000.0  ORD4     600
4    101    Alice   32         IT  75000.0  ORD5     100
5    102      Bob   30         HR  60000.0  ORD6      80
6    103  Charlie   32         IT  82000.0  ORD7      20
7    101    Alice   32         IT  75000.0  ORD8      50