In [15]:
from tokenize import group

import pandas as pd
import numpy as np
from datetime import datetime

employees_data = [
    {'EmpId': 'E01', 'Name': 'Alice', 'Age': 30, 'Gender': 'F', 'Dept_Code': 'IT', 'Married': False, 'Salary': 95000, 'DoJ': '2018-05-12', 'Years_Experience': 6},
    {'EmpId': 'E02', 'Name': 'Bob', 'Age': 45, 'Gender': 'M', 'Dept_Code': 'Fin', 'Married': True, 'Salary': 120000, 'DoJ': '2015-08-20', 'Years_Experience': 11},
    {'EmpId': 'E03', 'Name': 'Charlie', 'Age': 28, 'Gender': 'M', 'Dept_Code': 'IT', 'Married': False, 'Salary': 80000, 'DoJ': '2021-01-15', 'Years_Experience': 3},
    {'EmpId': 'E04', 'Name': 'Diana', 'Age': 35, 'Gender': 'F', 'Dept_Code': 'HR', 'Married': True, 'Salary': 90000, 'DoJ': '2019-11-01', 'Years_Experience': 7},
    {'EmpId': 'E05', 'Name': 'Eve', 'Age': 40, 'Gender': 'F', 'Dept_Code': 'RnD', 'Married': True, 'Salary': 110000, 'DoJ': '2016-03-10', 'Years_Experience': 10},
    {'EmpId': 'E06', 'Name': 'Frank', 'Age': 26, 'Gender': 'M', 'Dept_Code': 'Mkt', 'Married': False, 'Salary': 70000, 'DoJ': '2022-06-25', 'Years_Experience': 2},

     {'EmpId': 'E10', 'Name': 'X', 'Age': 30, 'Gender': 'F', 'Dept_Code': 'IT', 'Married': False, 'Salary': 120000, 'DoJ': '2026-05-12', 'Years_Experience': 6},
    {'EmpId': 'E11', 'Name': 'Y', 'Age': 30, 'Gender': 'M', 'Dept_Code': 'Fin', 'Married': True, 'Salary': 95000, 'DoJ': '2026-08-20', 'Years_Experience': 11},
    {'EmpId': 'E12', 'Name': 'X', 'Age': 28, 'Gender': 'M', 'Dept_Code': 'Mkt', 'Married': False, 'Salary': 80000, 'DoJ': '2026-01-15', 'Years_Experience': 3},
    {'EmpId': 'E13', 'Name': 'U', 'Age': 28, 'Gender': 'F', 'Dept_Code': 'HR', 'Married': True, 'Salary': 90000, 'DoJ': '2025-11-01', 'Years_Experience': 7},
    {'EmpId': 'E14', 'Name': 'V', 'Age': 40, 'Gender': 'F', 'Dept_Code': 'RnD', 'Married': False, 'Salary': 210000, 'DoJ': '2026-03-10', 'Years_Experience': 20},

]

departments_data = [
    {'Dept_Code': 'IT', 'Name': 'Information Technology', 'Building': 'Alpha', 'Floors': [2, 3]},
    {'Dept_Code': 'Fin', 'Name': 'Finance', 'Building': 'Beta', 'Floors': [1]},
    {'Dept_Code': 'HR', 'Name': 'Human Resources', 'Building': 'Alpha', 'Floors': [1]},
    {'Dept_Code': 'RnD', 'Name': 'Research and Development', 'Building': 'Gamma', 'Floors': [4, 5, 6]},
    {'Dept_Code': 'Mkt', 'Name': 'Marketing', 'Building': 'Beta', 'Floors': [2, 3]},
    {'Dept_Code': 'REW', 'Name': 'Real Estate', 'Building': 'Delta', 'Floors': [1]}
]

orders_data = [
    {'OrdId': 'O001', 'Date': '2024-05-15', 'EmpId': 'E01', 'Value': 1500.50, 'isTeamExpense': True},
    {'OrdId': 'O101', 'Date': '2026-05-15', 'EmpId': 'E01', 'Value': 2500.50, 'isTeamExpense': True},
    {'OrdId': 'O002', 'Date': '2024-06-22', 'EmpId': 'E02', 'Value': 450.00, 'isTeamExpense': False},
    {'OrdId': 'O102', 'Date': '2026-06-22', 'EmpId': 'E02', 'Value': 450.00, 'isTeamExpense': False},
    {'OrdId': 'O003', 'Date': '2026-06-25', 'EmpId': 'E01', 'Value': 200.00, 'isTeamExpense': False},
    {'OrdId': 'O004', 'Date': '2026-07-01', 'EmpId': 'E05', 'Value': 3000.00, 'isTeamExpense': True},
    {'OrdId': 'O005', 'Date': '2024-07-10', 'EmpId': 'E03', 'Value': 120.00, 'isTeamExpense': False},
    {'OrdId': 'O105', 'Date': '2026-07-10', 'EmpId': 'E03', 'Value': 1120.00, 'isTeamExpense': True},
    {'OrdId': 'O006', 'Date': '2026-07-15', 'EmpId': 'E04', 'Value': 550.00, 'isTeamExpense': True},
    {'OrdId': 'O007', 'Date': '2026-07-15', 'EmpId': 'E04', 'Value': 550.00, 'isTeamExpense': False},
    {'OrdId': 'O008', 'Date': '2026-07-15', 'EmpId': 'E04', 'Value': 300.00, 'isTeamExpense': False},
    {'OrdId': 'O009', 'Date': '2025-07-15', 'EmpId': 'E04', 'Value': 100.00, 'isTeamExpense': False},
    {'OrdId': 'O010', 'Date': '2024-07-15', 'EmpId': 'E04', 'Value': 100.00, 'isTeamExpense': False},
]

df_emp = pd.DataFrame(employees_data)
df_dept = pd.DataFrame(departments_data)
df_ord = pd.DataFrame(orders_data)

In [16]:
display(df_ord)
display(df_dept)
display(df_emp)

   OrdId        Date EmpId   Value  isTeamExpense
0   O001  2024-05-15   E01  1500.5           True
1   O101  2026-05-15   E01  2500.5           True
2   O002  2024-06-22   E02   450.0          False
3   O102  2026-06-22   E02   450.0          False
4   O003  2026-06-25   E01   200.0          False
5   O004  2026-07-01   E05  3000.0           True
6   O005  2024-07-10   E03   120.0          False
7   O105  2026-07-10   E03  1120.0           True
8   O006  2026-07-15   E04   550.0           True
9   O007  2026-07-15   E04   550.0          False
10  O008  2026-07-15   E04   300.0          False
11  O009  2025-07-15   E04   100.0          False
12  O010  2024-07-15   E04   100.0          False

  Dept_Code                      Name Building     Floors
0        IT    Information Technology    Alpha     [2, 3]
1       Fin                   Finance     Beta        [1]
2        HR           Human Resources    Alpha        [1]
3       RnD  Research and Development    Gamma  [4, 5, 6]
4       Mkt                 Marketing     Beta     [2, 3]
5       REW               Real Estate    Delta        [1]

,EmpId,Name,Age,Gender,Dept_Code,Married,Salary,DoJ,Years_Experience
0,E01,Alice,30,F,IT,False,95000,2018-05-12,6
1,E02,Bob,45,M,Fin,True,120000,2015-08-20,11
2,E03,Charlie,28,M,IT,False,80000,2021-01-15,3
3,E04,Diana,35,F,HR,True,90000,2019-11-01,7
4,E05,Eve,40,F,RnD,True,110000,2016-03-10,10
5,E06,Frank,26,M,Mkt,False,70000,2022-06-25,2
6,E10,X,30,F,IT,False,120000,2026-05-12,6
7,E11,Y,30,M,Fin,True,95000,2026-08-20,11
8,E12,X,28,M,Mkt,False,80000,2026-01-15,3
9,E13,U,28,F,HR,True,90000,2025-11-01,7
10,E14,V,40,F,RnD,False,210000,2026-03-10,20

### Question 2: Relational Merging and Averaging
Calculate the average salary of employees who have placed at least one team expense order,
grouped by the Department Building.

_Hint: Dept_code is not 1:1 with Building_

In [26]:
display(df_ord[df_ord['isTeamExpense'] == True].merge(df_emp, how='inner', on='EmpId'))
df_ord[df_ord['isTeamExpense'] == True].merge(df_emp, how='inner', on='EmpId').\
    groupby(by='Dept_Code')[['Salary']].mean()

,OrdId,Date,EmpId,Value,isTeamExpense,Name,Age,Gender,Dept_Code,Married,Salary,DoJ,Years_Experience
0,O001,2024-05-15,E01,1500.5,True,Alice,30,F,IT,False,95000,2018-05-12,6
1,O101,2026-05-15,E01,2500.5,True,Alice,30,F,IT,False,95000,2018-05-12,6
2,O004,2026-07-01,E05,3000.0,True,Eve,40,F,RnD,True,110000,2016-03-10,10
3,O105,2026-07-10,E03,1120.0,True,Charlie,28,M,IT,False,80000,2021-01-15,3
4,O006,2026-07-15,E04,550.0,True,Diana,35,F,HR,True,90000,2019-11-01,7

             Salary
Dept_Code
HR          90000.0
IT          90000.0
RnD        110000.0

In [36]:
#Avg
print("Incorrect Avg1: %d" % ((95000*2+80000)/3))
print("Incorrect Avg2: %d" % ((95000+80000)/2))

Incorrect Avg1: 90000
Incorrect Avg2: 87500

In [35]:
# Filter for team expenses and get unique employees
team_exp_emps = df_ord[df_ord['isTeamExpense']]['EmpId'].unique()
display(team_exp_emps)

# Filter employee dataframe
emp_team = df_emp[df_emp['EmpId'].isin(team_exp_emps)]
display(emp_team)

# Merge with departments to get building, then group by building
merged_bldg = emp_team.merge(df_dept, on='Dept_Code')
display(merged_bldg)

array(['E01', 'E05', 'E03', 'E04'], dtype=object)

,EmpId,Name,Age,Gender,Dept_Code,Married,Salary,DoJ,Years_Experience
0,E01,Alice,30,F,IT,False,95000,2018-05-12,6
2,E03,Charlie,28,M,IT,False,80000,2021-01-15,3
3,E04,Diana,35,F,HR,True,90000,2019-11-01,7
4,E05,Eve,40,F,RnD,True,110000,2016-03-10,10

,EmpId,Name_x,Age,Gender,Dept_Code,Married,Salary,DoJ,Years_Experience,Name_y,Building,Floors
0,E01,Alice,30,F,IT,False,95000,2018-05-12,6,Information Technology,Alpha,"[2, 3]"
1,E03,Charlie,28,M,IT,False,80000,2021-01-15,3,Information Technology,Alpha,"[2, 3]"
2,E04,Diana,35,F,HR,True,90000,2019-11-01,7,Human Resources,Alpha,[1]
3,E05,Eve,40,F,RnD,True,110000,2016-03-10,10,Research and Development,Gamma,"[4, 5, 6]"

In [ ]:
# More than one dept can be allocated the same bldg (e.g. 'Alpha')
print("Correct Avg (Bldg-wise): %d" % ((95000*2+80000)/3))

In [30]:
# Filter for team expenses and get unique employees
team_exp_emps = df_ord[df_ord['isTeamExpense']]['EmpId'].unique()

# Filter employee dataframe
emp_team = df_emp[df_emp['EmpId'].isin(team_exp_emps)]

# Merge with departments to get building, then group by building
merged_bldg = emp_team.merge(df_dept, on='Dept_Code')
avg_salary_bldg = merged_bldg.groupby('Building')['Salary'].mean()
print(avg_salary_bldg)

Building
Alpha     88333.333333
Gamma    110000.000000
Name: Salary, dtype: float64